[tool.bumpversion]
current_version = "16.0.0"
parse = "16\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["16.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = true
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = true
commit = false

[[tool.bumpversion.files]]
filename = "frappe_printrove/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'
